---
- name: Set configuration file
  sudo: yes
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  
- name: Create database directory
  sudo: yes
  file: path={{ mongodb_datadir_prefix }}mongodb state=directory owner=mongod group=mongod

- name: Start MongoDB
  sudo: yes
  command: mongod -f /etc/mongod.conf