---
# This Playbook uninstall MongoDB and remove all related files (include data!)

- hosts: all
  tasks:
    - name: Stopping MongoDB service
      sudo: yes
      service: name=mongod state=stopped
      
    - name: Uninstall MongoDB
      sudo: yes
      yum: name=mongodb-org state=absent
      
    - name: Remove config files
      sudo: yes
      command: rm /etc/mongod.conf
      
    - name: Remove log files
      sudo: yes
      command: rm -rf {{ mongodb_logdir_prefix }}mongodb
      
    - name: Remove data files
      sudo: yes
      command: rm -rf {{ mongodb_datadir_prefix }}mongodb