---
# This Playbook initialize MongoDB cluster with MongoDB running in Docker container

- name: Copy init script to tmp folder
  sudo: yes
  template: src=init_replset.j2 dest=/tmp/init_replset.js
  
- name: Pause to allow MongoDB service starts
  pause: seconds=6  
  
- name: Start mongo shell and initialize MongoDB replica set
  sudo: yes
  command: docker run -i -t --rm --link mongodb:mongodb -v /tmp:/tmp dockerfile/mongodb bash -c 'mongo --host $MONGODB_PORT_{{ mongod_port }}_TCP_ADDR /tmp/init_replset.js'